### ISSUE TITLE
Explore using poetry for package management further

### ISSUE THREAD

**Issue by ntelfer** [reputage/didery.py#80]
Poetry is significantly easier to use than setup.py, sdist, bdist_wheel, and twine.  However the first attempt at using it failed because it doesn't seem to let you specify an entry point for your app like setup.py does. See if there is a way to do this.

**Comment by SmithSamuelM** [comment]
While it may be true that Poetry is easier to use. The infrastructure around setup.py etc is so extensive that you are likely to have adoption problems if you abandon setup.py for poetry. If on the other hand you leave setup.py as the primary method but add optional support for poetry then that is not so problematic. Although its not clear what you gain since you have already incurred the cost of making the setup.py work.

**Comment by ntelfer** [comment]
Poetry is still in development and has not yet released a stable version. It is significantly easier to use but is still missing some needed functionality and community support.  We should revisit this in another year or two.
